### ISSUE TITLE
Memory data collection freezes firefox 38.0.1 for two or three seconds

### ISSUE THREAD

**Issue by gregist** [bobbyrne01/tab-data-firefox#17]
The freezing is noticeable and very annoying.

Any plans to make the polling process less intrusive?

**Comment by bobbyrne01** [comment]
hey @gregist yeah the polling is very noticeable. Unfortunately this cannot be solved yet given the current architecture of Firefox i.e UI and scripts run in a single process.

When the [Electrolysis](https://wiki.mozilla.org/Electrolysis) project is released in Firefox the freezing will no longer be an issue. You can try it out using a [nightly](https://nightly.mozilla.org/) build of Firefox which has electrolysis enabled by default.

**Comment by gregist** [comment]
Hi @bobbyrne01 I tried Nightly 41 with multi-process turned on. The hiccup got better, but still very noticeable. I am using win8.1 on x64 if relevant.

The Nightly version broke Vimperator though. ;) So I will stick to the beta channel.

I did not read the code but, Will polling one tab at a time make the case better?
