### ISSUE TITLE
Please Correct "ja-JP" Translation

### ISSUE THREAD

**Issue by RRRRRRRRwQ** [bobbyrne01/tab-data-firefox#23]
I made a draft.

addonName_title=Tab Data

memoryUsageLabel=メモリ
graphLabel=グラフ
countsLabelは=タブ数
settingsLabel=[設定]

openNow_title=現在開かれているタブ
openSession_title=現在のセッションで開かれたタブ
openInstall_title=このアドオンをインストールしてから開いたタブ

behaviour_title=挙動
ui_title=ユーザーインターフェース
tasks_title=タスク
graphType_title=グラフの種類
graphType_options.Line=面グラフ
graphType_options.Bar=棒グラフ
graphType_options.Radar=レーダーチャート
graphType_options.PolarArea=鶏頭図

memoryInterval_title=メモリのデータ収集の間隔
memoryTracking_title=メモリ使用量の追跡を有効にする
memoryUsageOnTabTitlesPref_title=メモリ使用量の表示
memoryUsageOnTabTitlesPref_options.Prepend=先頭
memoryUsageOnTabTitlesPref_options.Append=最後尾
memoryUsageOnTabTitlesPref_options.Disable=無効

memoryFormat_title=パネル上のメモリ使用量の形式
memoryFormat_options.JSON=JSON
memoryFormat_options.Plain=Plain

memoryCautionThreshold_title=メモリ使用量を警告する閾値 (メガバイト単位)
showUrl_title=パネルでURLを表示する
garbageCollection_title=ガベージコレクションを実行します
run_title=実行

panelWidth_title=パネルの幅
panelHeight_title=パネルの高さ

**Comment by bobbyrne01** [comment]
fixed on `master`, should be available on AMO in a few days once reviewed
