### ISSUE TITLE
Preference to toggle drawing graph on/off or add none to Graph types

### ISSUE THREAD

**Issue by martbase** [bobbyrne01/tab-data-firefox#25]

**Comment by bobbyrne01** [comment]
good idea :+1: ill add into next update

**Comment by bobbyrne01** [comment]
added to 0.5.9

should be available on [mozilla](https://addons.mozilla.org/en-US/firefox/addon/tab-data/) in a few days (awaiting review) or you can build from source in mean time.

**Comment by martbase** [comment]
I am not sure if this fix is the cause but before I raise another issue I wanted to report that after recently updating the add-on both the graph and memory tabs are now completely blank. The list of top five memory consumers has disappeared (see attached image).
![blank-graph-memory-tab](https://cloud.githubusercontent.com/assets/3264387/14013991/b6d98c3a-f1c0-11e5-86ce-b4917f80a0de.jpg)

**Comment by bobbyrne01** [comment]
im seeing same issue, will investigate

**Comment by bobbyrne01** [comment]
@martbase can you remove the addon and try version `0.5.10.1` please?

its working for me now. the addon was trying to use a file which was not part of the package.

**Comment by martbase** [comment]
Still not working for me even after removing and re-installing the addon. Both memory and graph tabs remain blank. I have attached my settings just in case...
![blank-graph-memory-tab-updt](https://cloud.githubusercontent.com/assets/3264387/14147516/8f670734-f6a4-11e5-911c-429fb48eb3a5.jpg)

**Comment by martbase** [comment]
Issue resolved! The tabs now show info as expected. Disregard previous post, I thought I had waited for 15mins or more when posting.

**Comment by bobbyrne01** [comment]
Good to hear :+1:

**Comment by martbase** [comment]
Actually I might have jumped the gun... I have two editions of Firefox - standard and developer edition. For the standard edition the graph setting is none and it exhibits the issue as described before. The developer edition has the graph setting set to line which now displays the top memory consumers as expected. 

It will be nice to display the top memory consumers whether or not a graph is displayed/shown i.e. graph type = none should also display the top memory consumers.

**Comment by bobbyrne01** [comment]
@martbase can you open a separate ticket to investigate this if it's still an issue please? I haven't been able to reproduce

**Comment by martbase** [comment]
Working correctly now. I restarted my laptop and I haven't been able to reproduce the the problem again. In case I do I will open a new ticket. Thanks for the great addon.

**Comment by bobbyrne01** [comment]
your welcome :+1:
