### ISSUE TITLE
Add Refresh button to update tab memory usage on demand

### ISSUE THREAD

**Issue by martbase** [bobbyrne01/tab-data-firefox#26]
![firefox-opentabs](https://cloud.githubusercontent.com/assets/3264387/12826841/13975708-cb8e-11e5-9773-1241bbe105a2.jpg)
Besides the scheduled timer updates it would be nice to have a Refresh button that will update memory usage right away.

My use case is 900s (15 mins) between memory data collection to avoid overburdening the browser as I usually have hundreds of tabs open and since I don't shut down my laptop for days (prefer sleep so I can resume where I left off) open tabs usually add up pretty fast. I could be reading an article which references other articles which I would open in new tabs for reading later - this can happen again on the next article, ... Since my schedule interval is quite long tab data sometimes displays tabs that I already closed as top memory consumers under the graph tab (memory tab not sorted so relying on graph tab for now).

Identifying tabs with highest memory consumption will be useful as I can read those articles first and close them to cut down on browser memory usage.

**Comment by bobbyrne01** [comment]
will add this soon. probably using a button on Settings tab under Tasks.

**Comment by martbase** [comment]
+1

**Comment by bobbyrne01** [comment]
added into 0.5.10
