### ISSUE TITLE
Cleanup tabs title when unload tabs memory report

### ISSUE THREAD

**Issue by yfdyh000** [bobbyrne01/tab-data-firefox#4]

**Comment by bobbyrne01** [comment]
Thanks for pointing this out @yfdyh000 

In version 0.3.0 all tab title's will have memory usage removed after addon uninstall/disable.

**Comment by bobbyrne01** [comment]
@yfdyh000 tab titles are now cleaned up in [v0.2.7](https://addons.mozilla.org/en-US/firefox/addon/tab-data/versions/?page=1#version-0.2.7)

**Comment by yfdyh000** [comment]
Looks good.
