### ISSUE TITLE
Palemoon icon

### ISSUE THREAD

**Issue by ghost** [bobbyrne01/tab-data-firefox#6]
Thank you for great add-on.
Please add support for Palemoon browser,
(it is not showing icon)

http://www.palemoon.org/

**Comment by bobbyrne01** [comment]
The addon is not compatible with palemoon. Certain `api` the addon uses and depends on are not shipped with palemoon.
So for me the addon will not even install, sample expected errors:

```
Error: Module `sdk/ui/button/toggle` is not found at resource://gre/modules/commonjs/sdk/ui/button/toggle.js
```

Sorry, but I don't expect this to work until the dependencies are shipped with palemoon.
